on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [Release, Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Get Conan
        run: |
          pip install -U wheel setuptools
          pip install -U conan
      - name: Fix Path on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: echo "::add-path::/home/runner/.local/bin"

      - name: Create Conan Profile
        run: conan profile new default --detect
      - name: Set C++11 ABI on Linux
        if: matrix.os == 'ubuntu-latest'
        run: conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Generate
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }}
      - name: Build
        run: cmake --build . --config ${{ matrix.build_mode }}
