on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [Release, Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: pip install conan
      - run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }}
      - run: cmake --build . --config ${{ matrix.build_mode }}
